directories:
  train: './data/train'
  val: './data/val'
  test: './data/test'
  annotations: './data/annotations'
  checkpoints: './model_chkpt'
  tensorboard: './runs'
  logs: './logs'

training: 
  device: 'cuda'
  cores: 4
  classes: 
    '0': 'background'
    '1': 'split'
    '2': 'seed'
    '3': 'pod'
  n_classes: 4
  resize_to: 3000

settings:
  n_epochs: 50
  batch_size: 4
  model_name: 'my_model'
  lr: 0.05
  momentum: 0.8
  gamma: 0.9
