# Basic train config
run_name: high_lr_grad_clip
device: cuda
directories:
  train_dir: data/images/train
  val_dir: data/images/val
  test_dir: data/images/test
  output_dir: outputs
  label_dir: data/annotations/coco_annotations.json
  log_dir: logs
  checkpoint_dir: model_checkpoints
  tensorboard_dir: runs
model:
  num_classes: 4 # total num object classes plus background (0)
  max_det: 500
optimizer:
  weight_decay: 0.000001
  lr: 0.03
  momentum: 0.99
scheduler:
  gamma: 0.9
dataloader:
  batch_size: 1
  shuffle: true
  drop_last: true
  pin_memory: true
general:
  epochs: 100
  subset_size: [0.05, 0.1, 0.2, 0.5, 1.0]
# transforms:
#   resize_dims: [3000, 3000]