# Basic train config
run_name: basic_fasterrcnn
device: cpu
directories:
  train_dir: data/images/train
  val_dir: data/images/val
  test_dir: data/images/test
  output_dir: outputs
  label_dir: data/annotations/coco_annotations.json
  log_dir: logs
  checkpoint_dir: model_checkpoints
  tensorboard_dir: runs
model:
  num_classes: 4 # total num object classes plus background (0)
  max_det: 500
optimizer:
  weight_decay: 0.00001
  lr: 0.01
  # momentum: 0.99
scheduler:
  gamma: 0.9
dataloader:
  batch_size: 1
  shuffle: true
  drop_last: true
  pin_memory: true
general:
  epochs: 2
  subset_size: [0.02, 0.03, ]
# transforms:
#   resize_dims: [3000, 3000]